[build]
  command = "npm run build"
  publish = "dist/frontend"

[[redirects]]
  from = "/api/*"
  to = "https://adaction-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
