services:
  - type: web
    name: adaction-backend
    env: java
    plan: free
    buildCommand: mvn clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
